In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Finance_Trends.csv")

In [14]:
data.head()

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Male,29,Yes,2,4,7,5,3,1,6,...,Less than 1 year,Weekly,20%-30%,Public Provident Fund,Health Care,Dividend,Fund Diversification,Assured Returns,Fixed Returns,Newspapers and Magazines
1,Male,28,Yes,2,3,6,5,1,4,7,...,Less than 1 year,Weekly,30%-40%,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Television
2,Female,28,Yes,2,3,7,5,4,1,6,...,3-5 years,Daily,10%-20%,Mutual Fund,Health Care,Dividend,Better Returns,Assured Returns,Risk Free,Financial Consultants
3,Male,19,Yes,2,3,7,4,6,1,5,...,More than 5 years,Monthly,10%-20%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free,Newspapers and Magazines
4,Male,32,Yes,2,4,7,5,3,1,6,...,More than 5 years,Weekly,10%-20%,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns,Financial Consultants

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   gender                             12000 non-null  object
 1   age                                12000 non-null  int64
 2   Investment_Avenues                 12000 non-null  object
 3   Mutual_Funds                       12000 non-null  int64
 4   Equity_Market                      12000 non-null  int64
 5   Debentures                         12000 non-null  int64
 6   Government_Bonds                   12000 non-null  int64
 7   Fixed_Deposits                     12000 non-null  int64
 8   PPF                                12000 non-null  int64
 9   Gold                               12000 non-null  int64
 10  Stock_Marktet                      12000 non-null  object
 11  Factor                             12000 non-null  object
 12  Objective                          12000 non-null  object
 13  Purpose                            12000 non-null  object
 14  Duration                           12000 non-null  object
 15  Invest_Monitor                     12000 non-null  object
 16  Expect                             12000 non-null  object
 17  Avenue                             12000 non-null  object
 18  What are your savings objectives?  12000 non-null  object
 19  Reason_Equity                      12000 non-null  object
 20  Reason_Mutual                      12000 non-null  object
 21  Reason_Bonds                       12000 non-null  object
 22  Reason_FD                          12000 non-null  object
 23  Source                             12000 non-null  object
dtypes: int64(8), object(16)
memory usage: 2.2+ MB

In [16]:
data.Investment_Avenues.value_counts()

Investment_Avenues
Yes    11082
No       918
Name: count, dtype: int64

In [41]:
data_filtered = data[data["Investment_Avenues"] == "Yes"]

In [42]:
data_filtered.drop(columns=["Investment_Avenues"], inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\1181998629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop(columns=["Investment_Avenues"], inplace=True)

In [43]:
data_filtered.drop(["Invest_Monitor", "Source"], axis=1, inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2124841215.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop(["Invest_Monitor", "Source"], axis=1, inplace=True)

In [44]:
data_filtered.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,...,Objective,Purpose,Duration,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
0,Male,29,2,4,7,5,3,1,6,Yes,...,Growth,Wealth Creation,Less than 1 year,20%-30%,Public Provident Fund,Health Care,Dividend,Fund Diversification,Assured Returns,Fixed Returns
1,Male,28,2,3,6,5,1,4,7,Yes,...,Capital Appreciation,Wealth Creation,Less than 1 year,30%-40%,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free
2,Female,28,2,3,7,5,4,1,6,Yes,...,Capital Appreciation,Wealth Creation,3-5 years,10%-20%,Mutual Fund,Health Care,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Yes,...,Capital Appreciation,Wealth Creation,More than 5 years,10%-20%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Yes,...,Growth,Wealth Creation,More than 5 years,10%-20%,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns

In [45]:
data_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11082 entries, 0 to 11999
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   gender                             11082 non-null  object
 1   age                                11082 non-null  int64
 2   Mutual_Funds                       11082 non-null  int64
 3   Equity_Market                      11082 non-null  int64
 4   Debentures                         11082 non-null  int64
 5   Government_Bonds                   11082 non-null  int64
 6   Fixed_Deposits                     11082 non-null  int64
 7   PPF                                11082 non-null  int64
 8   Gold                               11082 non-null  int64
 9   Stock_Marktet                      11082 non-null  object
 10  Factor                             11082 non-null  object
 11  Objective                          11082 non-null  object
 12  Purpose                            11082 non-null  object
 13  Duration                           11082 non-null  object
 14  Expect                             11082 non-null  object
 15  Avenue                             11082 non-null  object
 16  What are your savings objectives?  11082 non-null  object
 17  Reason_Equity                      11082 non-null  object
 18  Reason_Mutual                      11082 non-null  object
 19  Reason_Bonds                       11082 non-null  object
 20  Reason_FD                          11082 non-null  object
dtypes: int64(8), object(13)
memory usage: 1.9+ MB

In [46]:
data_filtered.Expect.value_counts()

Expect
30%-40%    3800
10%-20%    3647
20%-30%    3635
Name: count, dtype: int64

In [49]:
data_filtered["Expect"] = data_filtered["Expect"].replace({"10%-20%": "low", "20%-30%": "medium", "30%-40%": "high"})

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2388857316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Expect"] = data_filtered["Expect"].replace({"10%-20%": "low", "20%-30%": "medium", "30%-40%": "high"})

In [50]:
data_filtered.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,...,Objective,Purpose,Duration,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
0,Male,29,2,4,7,5,3,1,6,Yes,...,Growth,Wealth Creation,Less than 1 year,medium,Public Provident Fund,Health Care,Dividend,Fund Diversification,Assured Returns,Fixed Returns
1,Male,28,2,3,6,5,1,4,7,Yes,...,Capital Appreciation,Wealth Creation,Less than 1 year,high,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free
2,Female,28,2,3,7,5,4,1,6,Yes,...,Capital Appreciation,Wealth Creation,3-5 years,low,Mutual Fund,Health Care,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Yes,...,Capital Appreciation,Wealth Creation,More than 5 years,low,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Yes,...,Growth,Wealth Creation,More than 5 years,low,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns

In [51]:
data_filtered.Reason_Equity.value_counts()

Reason_Equity
Capital Appreciation    8740
Dividend                2034
Liquidity                308
Name: count, dtype: int64

In [52]:
data_filtered.Reason_Mutual.value_counts()

Reason_Mutual
Better Returns          6627
Fund Diversification    3604
Tax Benefits             851
Name: count, dtype: int64

In [53]:
data_filtered.Reason_Bonds.value_counts()

Reason_Bonds
Assured Returns    7883
Safe Investment    2897
Tax Incentives      302
Name: count, dtype: int64

In [54]:
data_filtered.Reason_FD.value_counts()

Reason_FD
Fixed Returns          5329
Risk Free              4882
High Interest Rates     871
Name: count, dtype: int64

In [55]:
#### Analyzing Low Expectation Group

data_low = data_filtered[data_filtered["Expect"] == "low"]

data_low.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,...,Objective,Purpose,Duration,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
2,Female,28,2,3,7,5,4,1,6,Yes,...,Capital Appreciation,Wealth Creation,3-5 years,low,Mutual Fund,Health Care,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Yes,...,Capital Appreciation,Wealth Creation,More than 5 years,low,Equity,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Yes,...,Growth,Wealth Creation,More than 5 years,low,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns
5,Male,31,2,4,7,5,3,1,6,Yes,...,Growth,Wealth Creation,Less than 1 year,low,Mutual Fund,Health Care,Dividend,Fund Diversification,Assured Returns,Fixed Returns
7,Male,30,3,4,6,5,2,1,7,Yes,...,Capital Appreciation,Wealth Creation,Less than 1 year,low,Public Provident Fund,Retirement Plan,Capital Appreciation,Better Returns,Assured Returns,Risk Free

In [56]:
data_filtered.Objective.value_counts()

Objective
Capital Appreciation    7159
Growth                  3341
Income                   582
Name: count, dtype: int64

In [57]:
data_filtered.Purpose.value_counts()

Purpose
Wealth Creation       9031
Savings for Future    1486
Returns                565
Name: count, dtype: int64

In [59]:
data_filtered.drop("What are your savings objectives?", axis=1, inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\1218328481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop("What are your savings objectives?", axis=1, inplace=True)

In [60]:
data_filtered.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,Factor,Objective,Purpose,Duration,Expect,Avenue,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
0,Male,29,2,4,7,5,3,1,6,Yes,Risk,Growth,Wealth Creation,Less than 1 year,medium,Public Provident Fund,Dividend,Fund Diversification,Assured Returns,Fixed Returns
1,Male,28,2,3,6,5,1,4,7,Yes,Returns,Capital Appreciation,Wealth Creation,Less than 1 year,high,Public Provident Fund,Capital Appreciation,Better Returns,Assured Returns,Risk Free
2,Female,28,2,3,7,5,4,1,6,Yes,Returns,Capital Appreciation,Wealth Creation,3-5 years,low,Mutual Fund,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Yes,Risk,Capital Appreciation,Wealth Creation,More than 5 years,low,Equity,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Yes,Returns,Growth,Wealth Creation,More than 5 years,low,Public Provident Fund,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns

In [61]:
data_filtered.drop("Avenue", axis=1, inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2013431723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop("Avenue", axis=1, inplace=True)

In [62]:
data_filtered.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,Factor,Objective,Purpose,Duration,Expect,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
0,Male,29,2,4,7,5,3,1,6,Yes,Risk,Growth,Wealth Creation,Less than 1 year,medium,Dividend,Fund Diversification,Assured Returns,Fixed Returns
1,Male,28,2,3,6,5,1,4,7,Yes,Returns,Capital Appreciation,Wealth Creation,Less than 1 year,high,Capital Appreciation,Better Returns,Assured Returns,Risk Free
2,Female,28,2,3,7,5,4,1,6,Yes,Returns,Capital Appreciation,Wealth Creation,3-5 years,low,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Yes,Risk,Capital Appreciation,Wealth Creation,More than 5 years,low,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Yes,Returns,Growth,Wealth Creation,More than 5 years,low,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns

In [63]:
data_filtered.drop("Duration", axis=1, inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\1372126280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop("Duration", axis=1, inplace=True)

In [64]:
data_filtered.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Stock_Marktet,Factor,Objective,Purpose,Expect,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
0,Male,29,2,4,7,5,3,1,6,Yes,Risk,Growth,Wealth Creation,medium,Dividend,Fund Diversification,Assured Returns,Fixed Returns
1,Male,28,2,3,6,5,1,4,7,Yes,Returns,Capital Appreciation,Wealth Creation,high,Capital Appreciation,Better Returns,Assured Returns,Risk Free
2,Female,28,2,3,7,5,4,1,6,Yes,Returns,Capital Appreciation,Wealth Creation,low,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Yes,Risk,Capital Appreciation,Wealth Creation,low,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Yes,Returns,Growth,Wealth Creation,low,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns

In [65]:
data_filtered.drop(["Factor","Stock_Marktet"], axis=1, inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\1242060855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop(["Factor","Stock_Marktet"], axis=1, inplace=True)

In [66]:
data_filtered.head()

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Objective,Purpose,Expect,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD
0,Male,29,2,4,7,5,3,1,6,Growth,Wealth Creation,medium,Dividend,Fund Diversification,Assured Returns,Fixed Returns
1,Male,28,2,3,6,5,1,4,7,Capital Appreciation,Wealth Creation,high,Capital Appreciation,Better Returns,Assured Returns,Risk Free
2,Female,28,2,3,7,5,4,1,6,Capital Appreciation,Wealth Creation,low,Dividend,Better Returns,Assured Returns,Risk Free
3,Male,19,2,3,7,4,6,1,5,Capital Appreciation,Wealth Creation,low,Capital Appreciation,Better Returns,Assured Returns,Risk Free
4,Male,32,2,4,7,5,3,1,6,Growth,Wealth Creation,low,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns

In [67]:
data_filtered["Total_investment_options"] = data_filtered["Mutual_Funds"] + data_filtered["Equity_Market"] + data_filtered["Debentures"] + data_filtered["Government_Bonds"] + data_filtered["Fixed_Deposits"] + data_filtered["PPF"] + data_filtered["Gold"]

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\264892070.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Total_investment_options"] = data_filtered["Mutual_Funds"] + data_filtered["Equity_Market"] + data_filtered["Debentures"] + data_filtered["Government_Bonds"] + data_filtered["Fixed_Deposits"] + data_filtered["PPF"] + data_filtered["Gold"]

In [68]:
### divide each investment option by total investment options to get the percentage of each investment option

data_filtered["Mutual_Funds_Percentage"] = data_filtered["Mutual_Funds"] / data_filtered["Total_investment_options"]
data_filtered["Equity_Market_Percentage"] = data_filtered["Equity_Market"] / data_filtered["Total_investment_options"]
data_filtered["Debentures_Percentage"] = data_filtered["Debentures"] / data_filtered["Total_investment_options"]
data_filtered["Government_Bonds_Percentage"] = data_filtered["Government_Bonds"] / data_filtered["Total_investment_options"]
data_filtered["Fixed_Deposits_Percentage"] = data_filtered["Fixed_Deposits"] / data_filtered["Total_investment_options"]
data_filtered["PPF_Percentage"] = data_filtered["PPF"] / data_filtered["Total_investment_options"]
data_filtered["Gold_Percentage"] = data_filtered["Gold"] / data_filtered["Total_investment_options"]
data_filtered.head()

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Mutual_Funds_Percentage"] = data_filtered["Mutual_Funds"] / data_filtered["Total_investment_options"]
C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Equity_Market_Percentage"] = data_filtered["Equity_Market"] / data_filtered["Total_investment_options"]
C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Debentures_Percentage"] = data_filtered["Debentures"] / data_filtered["Total_investment_options"]
C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Government_Bonds_Percentage"] = data_filtered["Government_Bonds"] / data_filtered["Total_investment_options"]
C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Fixed_Deposits_Percentage"] = data_filtered["Fixed_Deposits"] / data_filtered["Total_investment_options"]
C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["PPF_Percentage"] = data_filtered["PPF"] / data_filtered["Total_investment_options"]
C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\2482531459.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered["Gold_Percentage"] = data_filtered["Gold"] / data_filtered["Total_investment_options"]

,gender,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,Objective,...,Reason_Bonds,Reason_FD,Total_investment_options,Mutual_Funds_Percentage,Equity_Market_Percentage,Debentures_Percentage,Government_Bonds_Percentage,Fixed_Deposits_Percentage,PPF_Percentage,Gold_Percentage
0,Male,29,2,4,7,5,3,1,6,Growth,...,Assured Returns,Fixed Returns,28,0.071429,0.142857,0.250000,0.178571,0.107143,0.035714,0.214286
1,Male,28,2,3,6,5,1,4,7,Capital Appreciation,...,Assured Returns,Risk Free,28,0.071429,0.107143,0.214286,0.178571,0.035714,0.142857,0.250000
2,Female,28,2,3,7,5,4,1,6,Capital Appreciation,...,Assured Returns,Risk Free,28,0.071429,0.107143,0.250000,0.178571,0.142857,0.035714,0.214286
3,Male,19,2,3,7,4,6,1,5,Capital Appreciation,...,Assured Returns,Risk Free,28,0.071429,0.107143,0.250000,0.142857,0.214286,0.035714,0.178571
4,Male,32,2,4,7,5,3,1,6,Growth,...,Assured Returns,Fixed Returns,28,0.071429,0.142857,0.250000,0.178571,0.107143,0.035714,0.214286

In [69]:
data_filtered.drop(["Mutual_Funds", "Equity_Market", "Debentures", "Government_Bonds", "Fixed_Deposits", "PPF", "Gold"], axis=1, inplace=True)

C:\Users\Z004DNCE\AppData\Local\Temp\ipykernel_25964\3941886395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered.drop(["Mutual_Funds", "Equity_Market", "Debentures", "Government_Bonds", "Fixed_Deposits", "PPF", "Gold"], axis=1, inplace=True)

In [70]:
data_filtered.head()

,gender,age,Objective,Purpose,Expect,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Total_investment_options,Mutual_Funds_Percentage,Equity_Market_Percentage,Debentures_Percentage,Government_Bonds_Percentage,Fixed_Deposits_Percentage,PPF_Percentage,Gold_Percentage
0,Male,29,Growth,Wealth Creation,medium,Dividend,Fund Diversification,Assured Returns,Fixed Returns,28,0.071429,0.142857,0.250000,0.178571,0.107143,0.035714,0.214286
1,Male,28,Capital Appreciation,Wealth Creation,high,Capital Appreciation,Better Returns,Assured Returns,Risk Free,28,0.071429,0.107143,0.214286,0.178571,0.035714,0.142857,0.250000
2,Female,28,Capital Appreciation,Wealth Creation,low,Dividend,Better Returns,Assured Returns,Risk Free,28,0.071429,0.107143,0.250000,0.178571,0.142857,0.035714,0.214286
3,Male,19,Capital Appreciation,Wealth Creation,low,Capital Appreciation,Better Returns,Assured Returns,Risk Free,28,0.071429,0.107143,0.250000,0.142857,0.214286,0.035714,0.178571
4,Male,32,Growth,Wealth Creation,low,Capital Appreciation,Better Returns,Assured Returns,Fixed Returns,28,0.071429,0.142857,0.250000,0.178571,0.107143,0.035714,0.214286

In [73]:
reason_equity = data_filtered["Reason_Equity"].unique()

In [74]:
reason_equity

array(['Dividend', 'Capital Appreciation', 'Liquidity'], dtype=object)

In [75]:
reason_mutual = data_filtered["Reason_Mutual"].unique()

In [76]:
reason_bonds = data_filtered["Reason_Bonds"].unique()

In [77]:
reason_fd = data_filtered["Reason_FD"].unique()

In [ ]:
dict_reason_equity = {"Equity": reason_equity, "Mutual": reason_mutual, "Bonds": reason_bonds, "FD": reason_fd}